installer:
  repo: "devtron-labs/devtron-installation-script"
  release: "main"
#Use secrets in plaintext, they'll be encoded to base64 automatically.
secrets:
  data:
  - key: POSTGRESQL_PASSWORD
    value: "change-me"

#  Token with read write access to AZURE_BLOB_CONTAINER_CI_LOG and AZURE_BLOB_CONTAINER_CI_CACHE ,optional, if not
#  provided pod identity will be used for authentication
#  - key: AZURE_ACCOUNT_KEY
#    value: "#########"

configs:
  BLOB_STORAGE_PROVIDER: "MINIO"   #AZURE|AWS|MINIO
# Amazon AWS S3 bucket and region for storing Build-cache for faster build process. Mandatory if BLOB_STORAGE_PROVIDER is AWS.
  #DEFAULT_CACHE_BUCKET: "us-east-1"   #Do not include s3://
  #DEFAULT_CACHE_BUCKET_REGION: "change-me"
# Amazon AWS S3 bucket and region for storing Build-logs. Mandatory if BLOB_STORAGE_PROVIDER is AWS.
  #DEFAULT_BUILD_LOGS_BUCKET: "change-me"   #Do not include s3://
  #DEFAULT_CD_LOGS_BUCKET_REGION: "us-east-1"
# Amazon AWS Secret Region if you will be using AWS Secret manager for storing secrets.
  #EXTERNAL_SECRET_AMAZON_REGION: ""
# Azure Blob storage Info for storing Build Logs and Build cache for faster build process.
  #AZURE_ACCOUNT_NAME: "test-account"
  #AZURE_BLOB_CONTAINER_CI_LOG: "ci-log-container"
  #AZURE_BLOB_CONTAINER_CI_CACHE: "ci-cache-container"