apiVersion: v1
kind: Secret
metadata:
  name: devtron-operator-secret
  namespace: devtroncd
type: Opaque
data:
  {{ if .Values.secrets.data.[POSTGRESQL_PASSWORD] }}
  db-password:  {{ .Values.secrets.data.[POSTGRESQL_PASSWORD] | b64enc }}
  {{ else }}
  db-password: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
  {{- range $.Values.secrets.data }}
  {{ .key | quote }}: {{ .value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devtron-operator-cm
  namespace: devtroncd
data:
    {{- if .Values.configs }}
{{ toYaml $.Values.configs | indent 2 }}
    {{- end }}
