apiVersion: installer.devtron.ai/v1alpha1
kind: Installer
metadata:
  name: installer-devtron
  namespace: devtroncd
spec:
  url: https://raw.githubusercontent.com/{{ .Values.installer.repo }}/{{ .Values.installer.release }}/installation-script
